### ISSUE TITLE
Testing non-zero exit codes

### ISSUE THREAD

**Issue by paulwib** [bmizerany/roundup#40]
Is there a way to test my script has a non-zero exit code i.e. it errors as expected under certain conditions? It seems that roundup will always exit?

**Comment by paulwib** [comment]
Ah, never mind, I found a way:

``` bash
it_should_exit_with_error_code_23 () {
    bash ../scripts/execute.sh || test $? -eq 23
}
```

**Comment by paulwib** [comment]
Actually no, that was false positive ;) Any ideas?

**Comment by raphaelahrens** [comment]
I always use something like this.

```
it_test () {
      test 23 -eq $(bash ../scripts/execute.sh   > /dev/null; echo $?)
}
```

But maybe you could write a script for just testing the exit code.
So that you could write

```
it_test () {
      test_exit  23 bash ../scripts/execute.sh
}
```

The script/function could look similar to the following, but this is just a spontaneous idea and nor really tested. 

```
#!/bin/sh

exit_code="$1"
shift 1

($*)

if [ $? -eq "$exit_code" ]; then
    exit 0
fi

printf "%d\n" "$?"
exit 1
```

**Comment by paulwib** [comment]
Thanks, but that didn't work for me, the result was always empty. In the end I went with switching shell error handling off and on e.g.

```
it_should_exit_with_error_code_23 () {
    set +e && (bash ../scripts/execute.sh) && set -e
    test 23 -eq $?
}
```
